version: '3.4'

networks:
  nginx-proxy:

services:
  chatbot:
    extends:
      file: hahs-teams-bot/docker-compose.yml
      service: chatbot
    network_mode: "bridge"
    networks:
      - nginx-proxy
    ports:
      - "3978:3978"

  token:
    extends:
      file: hahs-teams-bot/docker-compose.yml
      service: token
    network_mode: "bridge"
    networks:
      - nginx-proxy

  swag:
    # image: linuxserver/swag:2.2.0
    build:
      dockerfile: nginx/swag.Dockerfile
    depends_on:
      - chatbot
    volumes:
      - /var/docker/letsencrypt/config:/config
      - ./nginx/proxy:/config/nginx/proxy-confs
      - ./nginx/content:/config/www/content
      - ./nginx/default.conf:/config/nginx/site-confs/default.conf
      - ./nginx/content/website:/config/www/content/website
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - nginx-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - URL=hahs.app
      - VALIDATION=http
      - SUBDOMAINS=www,chatbot,
      - VALIDATION=dns
      - DNSPLUGIN=digitalocean
      - EMAIL
      - ONLY_SUBDOMAINS=false
      - DHLEVEL=4096
      - STAGING=false
    container_name: swag
    ports:
      - 443:443
      - 80:80
